version: '3.8'

services:
  backtotheblack:
    image: backtotheblack/web:latest.${GITHUB_RUN_ID}
    ports:
      - 80:8000
    volumes:
      - /data/models:/app/models:ro
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - backtotheblack-network

networks:
  backtotheblack-network: