version: '3.8'
services:
  backtotheblack:
    image: backtotheblack/web:latest.${GITHUB_RUN_ID}
    ports:
      - published: 80
        target: 8000
        protocol: tcp
        mode: host
    volumes:
      - /data/models:/app/models:ro
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - backtotheblack-network
networks:
  backtotheblack-network: