version: 1

formatters:
  default:
    '()': uvicorn.logging.DefaultFormatter
    format: '%(asctime)s - %(levelname)s - %(message)s'
    use_colors: False
  access:
    '()': uvicorn.logging.AccessFormatter
    format: '%(asctime)s - %(levelname)s - %(message)s'
    use_colors: False

handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stderr
  access:
    class: logging.StreamHandler
    formatter: access
    stream: ext://sys.stdout

loggers:
  uvicorn:
    level: INFO
    handlers: [default]
    propagate: True
  uvicorn.error:
    level: INFO
    handlers: [default]
    propagate: True
  uvicorn.access:
    level: INFO
    handlers: [access]
    propagate: False

root:
  level: INFO
  handlers: [default]